version: "3"

services:
  database:
    image: "postgres:latest"
    container_name: '${DB_CONTAINER_NAME}'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data' 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_MACHINE_POSTGRES_PORT}:5432"


  appscala:
    image: "users:0.0.1-SNAPSHOT"
    container_name: '${APPSCALA_CONTAINER_NAME}'
    links:
      - database
    restart: 'always'
    ports:
      - "${HOST_MACHINE_APPSCALA_PORT}:8000"
    depends_on:
      - database
